weights: ../drive/My Drive/Yolov5_cpt/exp2/weights/best.pt
cfg: ''
data: ./data/data.yaml
hyp: data/hyps/hyp.scratch.yaml
epochs: 100
batch_size: 16
img_size:
- 1280
- 1280
rect: false
resume: true
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache_images: false
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 8
project: ../drive/My Drive/Yolov5_cpt
entity: null
name: exp
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
local_rank: -1
save_dir: ../drive/My Drive/Yolov5_cpt/exp2
